services:
  database:
    image: mariadb:latest
    container_name: "game_database"
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./database/init.sql:/data/application/init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: game
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  server:
    build:
      context: .
    restart: always
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    env_file:
      - .env
    command: ["npm", "run", "dev"]
